### ISSUE TITLE
Project not running

### ISSUE THREAD

**Issue by prabeshshrestha** [toytown/ecom#1]
I am getting some wicket error trying to run the application . Attached is the screenshot of the error page ... 

![Screen Shot 2013-01-22 at 8 06 12 PM](https://f.cloud.github.com/assets/538544/87544/fe90f278-64c6-11e2-9c11-39fc6956cf26.png)

**Comment by toytown** [comment]
try with tomcat 6..looks to me some rendering issue with the servlet
container
